### ISSUE TITLE
Issue using new WebError(404)

### ISSUE THREAD

**Issue by veilevil** [seeden/web-error#1]
When I run the exsample code in my expressjs app, it throws an error:

`TypeError: WebError is not a function`

This is my code:

```
function adminController(req, res, next) {
  var WebError = require('web-error');
  var error = new WebError(404);
  return next(error);
}
```

**Comment by seeden** [comment]
I released new version with updated Readme. Please take a look on it. 
If you are using CommonJS syntax you need to use require('web-error').default
